#!/usr/bin/env python3
"""Generate the handler-spawned NPC ID table compiled into Aion.GameServer."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
HANDLER_ROOTS = (
    REPO_ROOT / "src/Aion.GameServer/Handlers/Instance",
    REPO_ROOT / "src/Aion.GameServer/Handlers/Quest",
    REPO_ROOT / "src/Aion.GameServer/Handlers/AI",
)
OUTPUT = REPO_ROOT / "src/Aion.GameServer/Questengine/HandlerSpawnedNpcIds.cs"
SPAWN_ARGUMENT = re.compile(r"\bSpawn\s*\((?P<argument>[^,\r\n]*)")
NPC_ID = re.compile(r"(?<!\d)\d{6}(?!\d)")


def collect_ids() -> list[int]:
    npc_ids: set[int] = set()
    for root in HANDLER_ROOTS:
        for path in sorted(root.rglob("*.cs")):
            source = path.read_text(encoding="utf-8-sig")
            for match in SPAWN_ARGUMENT.finditer(source):
                npc_ids.update(int(value) for value in NPC_ID.findall(match.group("argument")))
    return sorted(npc_ids)


def render(npc_ids: list[int]) -> str:
    rows = []
    for index in range(0, len(npc_ids), 12):
        rows.append("        " + ", ".join(str(value) for value in npc_ids[index : index + 12]) + ",")
    values = "\n".join(rows)
    return f"""// <auto-generated>
// Generated by scripts/e2e/generate-handler-spawn-ids.py from Handlers/{{Instance,Quest,AI}}/**/*.cs.
// Do not edit by hand; run the generator and commit the result.
// </auto-generated>

namespace Aion.GameServer.QuestEngine;

internal static class HandlerSpawnedNpcIds
{{
    internal static readonly int[] All =
    [
{values}
    ];
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when the checked-in table is stale")
    args = parser.parse_args()

    generated = render(collect_ids())
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8-sig") != generated:
            print(f"stale handler-spawn table: {OUTPUT.relative_to(REPO_ROOT)}")
            return 1
        print(f"handler-spawn table is current ({len(collect_ids())} NPC ids)")
        return 0

    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} ({len(collect_ids())} NPC ids)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
