#!/bin/bash
# Writes the highest-precedence GameServer config override (mygs.properties) from environment
# variables provided by docker-compose / .env, then launches the server. No game code change needed.
set -e

cat > /app/game-server/config/mygs.properties <<EOF
# AUTO-GENERATED by the docker entrypoint from environment / .env — do not edit by hand.
database.url = jdbc:mysql://${DB_HOST:-mysql}:${DB_PORT:-3306}/aion_gs?characterEncoding=UTF-8
database.user = ${DB_USER:-root}
database.password = ${DB_PASSWORD:-aion}

# Address handed to clients (what the login server advertises for this game server).
gameserver.network.client.connect_address = ${SERVER_HOST:-127.0.0.1}:${GAME_CLIENT_PORT:-7777}
# Internal bind inside the container (host port is mapped by compose).
gameserver.network.client.socket_address = 0.0.0.0:7777
# Cross-server bridges over the docker network.
gameserver.network.login.address = ${LOGIN_ADDRESS:-loginserver:9014}
gameserver.network.chat.address = ${CHAT_ADDRESS:-chatserver:9021}

# Gameplay knobs.
gameserver.custom.respawn.time_multiplier = ${RESPAWN_TIME_MULTIPLIER:-1.0}
EOF

# A bot/test stack may mount read-only overrides here. Files are appended in glob order so the generated
# deployment values above remain today's defaults when no overlay is present, while overlays win when mounted.
# The optional instance overlay supplies topology (for example GS id/database) after the shared profile.
for overlay_dir in "${AION_CONFIG_OVERLAY_DIR:-/app/config-overlay}" "${AION_CONFIG_INSTANCE_OVERLAY_DIR:-/app/instance-overlay}"; do
if [ -d "$overlay_dir" ]; then
    for overlay in "$overlay_dir"/*.properties; do
        [ -f "$overlay" ] || continue
        printf '\n# Overlay: %s\n' "$(basename "$overlay")" >> /app/game-server/config/mygs.properties
        cat "$overlay" >> /app/game-server/config/mygs.properties
        printf '\n' >> /app/game-server/config/mygs.properties
    done
fi
done

cd /app
exec dotnet Aion.GameServer.dll
