#!/usr/bin/env python3
"""Generate the bot's SM_SYSTEM_MESSAGE id-to-STR_ name table from the C# catalog."""

from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path


REPO = Path(__file__).resolve().parents[2]
SOURCE = REPO / "src/Aion.GameServer/Network/Aion/ServerPackets/SM_SYSTEM_MESSAGE.cs"
OUTPUT = REPO / "tests/Aion.Bots/Protocol/SystemMessageNames.g.cs"
SIGNATURE = re.compile(r"public static SM_SYSTEM_MESSAGE (STR_\w+)\s*\([^)]*\)\s*\{")
DIRECT_ID = re.compile(r"return new SM_SYSTEM_MESSAGE\((\d+)")
DELEGATE = re.compile(r"return (STR_\w+)\(")


def factory_bodies(text: str) -> list[tuple[str, str]]:
    factories: list[tuple[str, str]] = []
    for match in SIGNATURE.finditer(text):
        depth = 1
        cursor = match.end()
        while depth and cursor < len(text):
            if text[cursor] == "{":
                depth += 1
            elif text[cursor] == "}":
                depth -= 1
            cursor += 1
        if depth:
            raise SystemExit(f"Unbalanced factory body for {match.group(1)}")
        factories.append((match.group(1), text[match.end() : cursor - 1]))
    return factories


def generate() -> str:
    source = SOURCE.read_text(encoding="utf-8")
    factories = factory_bodies(source)
    ids_by_name: dict[str, int] = {}
    unresolved: list[tuple[str, str]] = []
    for name, body in factories:
        direct = DIRECT_ID.search(body)
        if direct:
            ids_by_name[name] = int(direct.group(1))
        else:
            delegated = DELEGATE.search(body)
            if not delegated:
                raise SystemExit(f"Factory {name} has no numeric or delegated SM_SYSTEM_MESSAGE return")
            unresolved.append((name, delegated.group(1)))
    while unresolved:
        pending: list[tuple[str, str]] = []
        for name, target in unresolved:
            if target in ids_by_name:
                ids_by_name[name] = ids_by_name[target]
            else:
                pending.append((name, target))
        if len(pending) == len(unresolved):
            raise SystemExit(f"Could not resolve delegated factories: {pending}")
        unresolved = pending

    # The source contains overloads and a few aliases. Preserve source order and use
    # the first STR_ name for each id so the bot's display name remains stable.
    names_by_id: dict[int, str] = {}
    for name, _ in factories:
        names_by_id.setdefault(ids_by_name[name], name)

    digest = hashlib.sha256(source.encode("utf-8")).hexdigest().upper()
    lines = [
        "// <auto-generated />",
        "#nullable enable",
        "using System.Collections.Frozen;",
        "",
        "namespace Aion.Bots.Protocol;",
        "",
        "public static class SystemMessageNames",
        "{",
        f"\tpublic const int FactoryCount = {len(factories)};",
        f'\tpublic const string SourceSha256 = "{digest}";',
        "",
        "\tprivate static readonly FrozenDictionary<int, string> Names =",
        "\t\tnew Dictionary<int, string>",
        "\t\t{",
    ]
    lines.extend(f'\t\t\t[{message_id}] = "{name}",' for message_id, name in sorted(names_by_id.items()))
    lines.extend(
        [
            "\t\t}.ToFrozenDictionary();",
            "",
            "\tpublic static IReadOnlyDictionary<int, string> All => Names;",
            "",
            "\tpublic static string? GetNameOrNull(int messageId) => Names.GetValueOrDefault(messageId);",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the generated file is stale")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            print(f"stale generated file: {OUTPUT.relative_to(REPO)}")
            return 1
        print(f"system-message name table is current ({SystemMessageSummary(generated)})")
        return 0
    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(REPO)} ({SystemMessageSummary(generated)})")
    return 0


def SystemMessageSummary(generated: str) -> str:
    count = re.search(r"FactoryCount = (\d+)", generated)
    entries = generated.count("\n\t\t\t[")
    return f"{count.group(1) if count else '?'} factories, {entries} ids"


if __name__ == "__main__":
    raise SystemExit(main())
