<#
.SYNOPSIS
Regenerate the starter-zone Java geo oracle (parity-artifacts/golden/geo) after a spawn or walker change.

.DESCRIPTION
GoldenGeoFixtureTests hashes every starter spawn/walker XML and checks 4,000+ spawn points against
heights and rays generated by the Java 4.8 geo engine. Any edit to a starter spawn file (a retail
placement pass, a removed camp, a re-snapped height) therefore fails it until the fixture is
regenerated from Java. This script does what parity-artifacts/golden/geo/README.md describes:
switch the Java checkout to its existing generator branch, run the generator, restore the 4.8
branch, then run the C# test against the new fixture. It creates no branch and no worktree.

Usage (from the C# repository root):
  pwsh -NoProfile -File scripts/parity/regen-geo-golden.ps1
BEYOND_AION_JAVA_ROOT names the Java checkout when it is not ../aion-server.
#>
$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$java = if ($env:BEYOND_AION_JAVA_ROOT) { $env:BEYOND_AION_JAVA_ROOT } else { Join-Path $root '..\aion-server' }
$java = (Resolve-Path $java).Path
$generatorBranch = 'codex/e2e-fixture-generators'
$specBranch = '4.8'

if (git -C $java status --porcelain) { throw "Java checkout $java is not clean; commit or stash it first." }
$before = (git -C $java branch --show-current).Trim()
if ($before -ne $specBranch) { throw "Java checkout is on '$before', expected '$specBranch'." }
if (-not (git -C $java branch --list $generatorBranch)) { throw "Java checkout has no '$generatorBranch' branch (see the golden README)." }

Write-Host "Java oracle: $java ($generatorBranch)"
git -C $java checkout -q $generatorBranch
try {
    Push-Location $java
    try {
        mvn -q -pl game-server -am '-Dmaven.test.skip=false' '-Dtest=GoldenGeoFixtureGeneratorTest' `
            '-Dsurefire.failIfNoSpecifiedTests=false' '-DargLine=-Xmx4g' test 2>&1 |
            Where-Object { $_ -match 'GEO GOLDEN|ERROR|BUILD' } | ForEach-Object { Write-Host $_ }
        if ($LASTEXITCODE -ne 0) { throw "Java generator failed (exit $LASTEXITCODE)." }
    } finally { Pop-Location }
} finally {
    git -C $java checkout -q $specBranch
    Write-Host "Java checkout restored to $((git -C $java branch --show-current).Trim())"
}

$manifest = Get-Content (Join-Path $root 'parity-artifacts/golden/geo/starter-inputs.json') | ConvertFrom-Json
Write-Host "Fixture regenerated: $($manifest.points) points. Verifying with the C# test..."
dotnet test (Join-Path $root 'tests/Aion.GameServer.Tests/Aion.GameServer.Tests.csproj') --filter 'FullyQualifiedName~GoldenGeoFixtureTests' 2>&1 |
    Where-Object { $_ -match 'Passed!|Failed!| error ' } | ForEach-Object { Write-Host $_ }
if ($LASTEXITCODE -ne 0) { throw 'GoldenGeoFixtureTests failed against the regenerated fixture.' }
Write-Host 'Done. Update the counts in parity-artifacts/golden/geo/README.md and commit the fixture with the spawn change.'
