#!/bin/bash
# Writes the ChatServer config override (mycs.properties) from environment, then launches.
set -e

cat > /app/chat-server/config/mycs.properties <<EOF
# AUTO-GENERATED by the docker entrypoint from environment / .env — do not edit by hand.
database.url = jdbc:mysql://${DB_HOST:-mysql}:${DB_PORT:-3306}/aion_cs?characterEncoding=UTF-8
database.user = ${DB_USER:-root}
database.password = ${DB_PASSWORD:-aion}

# Address handed to clients; internal bind + GS bridge bind.
chatserver.network.client.connect_address = ${SERVER_HOST:-127.0.0.1}:${CHAT_CLIENT_PORT:-10241}
chatserver.network.client.socket_address = 0.0.0.0:10241
chatserver.network.gameserver.socket_address = 0.0.0.0:9021
EOF

# A bot/test stack may mount read-only overrides here. Files are appended in glob order so the generated
# deployment values above remain today's defaults when no overlay is present, while overlays win when mounted.
for overlay_dir in "${AION_CONFIG_OVERLAY_DIR:-/app/config-overlay}" "${AION_CONFIG_INSTANCE_OVERLAY_DIR:-/app/instance-overlay}"; do
if [ -d "$overlay_dir" ]; then
    for overlay in "$overlay_dir"/*.properties; do
        [ -f "$overlay" ] || continue
        printf '\n# Overlay: %s\n' "$(basename "$overlay")" >> /app/chat-server/config/mycs.properties
        cat "$overlay" >> /app/chat-server/config/mycs.properties
        printf '\n' >> /app/chat-server/config/mycs.properties
    done
fi
done

cd /app
exec dotnet Aion.ChatServer.dll
