using System.Text.Json;
using System.Text.Json.Serialization;
using Aion.Bots.World;

namespace Aion.Bots.Navigation.NavMesh;

public enum BotTravelNodeKind
{
	Npc,
	BindPoint,
	Portal,
	Gather,
	Road,
}

public sealed record BotTravelNode(int Id, BotTravelNodeKind Kind, string Name, int TemplateId, BotPosition Position);

/// <summary>One verified walk link. <see cref="Danger"/> lists the aggressive spawn groups whose aggro
/// circles the checked route passes through, so a planner can weigh them by the bot's level.</summary>
public sealed record BotTravelEdge(int From, int To, float Length, float RoadFraction, IReadOnlyList<BotTravelDanger> Danger);

public sealed record BotTravelDanger(int NpcId, int Level, float Metres);

/// <summary>A server teleport offered by a portal NPC on this map (Java <c>portal_use</c>/<c>portal_dialog</c>).</summary>
public sealed record BotTravelExit(int From, int NpcId, int LocId, int TargetMapId, BotPosition Target, int MinLevel, int Kinah);

/// <summary>
/// Per-map "roads with branches": hub nodes (quest and service NPCs, bind points, portals, gather
/// clusters, road junctions) joined by walk links that each passed the navmesh router's collision-checked
/// route. Generated by <c>tools/Aion.NavBake graph</c>; never hand-edited. Stored as
/// <c>game-server/data/nav/&lt;mapId&gt;.graph.json</c>.
/// </summary>
public sealed record BotTravelGraph
{
	public int MapId { get; init; }
	public string MapName { get; init; } = "";
	public string NavMeshSha256 { get; init; } = "";
	public List<BotTravelNode> Nodes { get; init; } = [];
	public List<BotTravelEdge> Edges { get; init; } = [];
	public List<BotTravelExit> Exits { get; init; } = [];

	public static readonly JsonSerializerOptions Json = new()
	{
		WriteIndented = false,
		PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
		Converters = { new JsonStringEnumConverter() },
	};

	public static string PathFor(string repoRoot, int mapId) =>
		Path.Combine(BotNavMeshSet.DefaultDirectory(repoRoot), mapId + ".graph.json");

	public static BotTravelGraph? Load(string path) =>
		File.Exists(path) ? JsonSerializer.Deserialize<BotTravelGraph>(File.ReadAllText(path), Json) : null;

	public void Save(string path) => File.WriteAllText(path, JsonSerializer.Serialize(this, Json) + "\n");

	/// <summary>Nodes of a kind whose name or template matches, nearest first to <paramref name="near"/>.</summary>
	public IEnumerable<BotTravelNode> Find(int templateId, BotPosition? near = null) => Nodes
		.Where(n => n.TemplateId == templateId)
		.OrderBy(n => near is BotPosition p ? (n.Position.X - p.X) * (n.Position.X - p.X) + (n.Position.Y - p.Y) * (n.Position.Y - p.Y) : 0);
}
